version: '2'

#docker images build -> save docker images -> docker images run

services:
  config-server:
#    container_name: config-server
#    image: config-server
    build: ../netoss/config
    ports:
      - "8888/tcp"

  eureka-server:
#    container_name: eureka-server
#    image: eureka-server
    build: ../netoss/eureka
    ports:
      - "9999/tcp"

  gateway-server:
#    container_name: gateway-server
#    image: gateway-server
    build: ../netoss/gateway
    ports:
      - "7777/tcp"

#  service1-server:
#    container_name: service1-server
#    build:
#      context: docker-service1-server
#      dockerfile: Dockerfile
#    image: gateway-server:latest
#    ports:
#      - "8081/tcp"
#    networks:
#      - spring-cloud-network
#
#  service2-server:
#    container_name: service2-server
#    build:
#      context: docker-service2-server
#      dockerfile: Dockerfile
#    image: service2-server:latest
#    ports:
#      - "8082/tcp"
#    networks:
#      - spring-cloud-network
#
#  service3-server:
#    container_name: service3-server
#    build:
#      context: docker-service3-server
#      dockerfile: Dockerfile
#    image: service3-server:latest
#    ports:
#      - "8083/tcp"
#    networks:
#      - spring-cloud-network

#networks:
#  spring-cloud-network:
#    driver: bridge